<?php

namespace Database\Factories;

use App\Models\Ingredients;
use App\Models\Recipe;
use App\Models\Step;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Recipe>
 */
class RecipeFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->words(2, true).' Recipe',
            'description' => fake()->paragraph(),
            'author_email' => fake()->safeEmail(),
            'slug' => null, // Will be auto-generated by the model's boot method
        ];
    }

    /**
     * Configure the model factory.
     */
    public function configure(): static
    {
        return $this->afterCreating(function (Recipe $recipe) {
            // Only attach default ingredients if none are already attached
            if ($recipe->ingredients()->count() === 0) {
                $amounts = ['1/4', '1/3', '1/2', '2/3', '3/4', '1', '2', '3', '4', '5'];
                $units = ['cup', 'tbsp', 'tsp', 'clove', 'pinch', 'oz', 'lb', 'g', 'ml', 'l'];
                // Create some random ingredients and attach them to the recipe
                $ingredientCount = fake()->numberBetween(2, 4);
                $ingredients = Ingredients::count() > 10
                    ? Ingredients::inRandomOrder()->take($ingredientCount)->get()
                    : Ingredients::factory()->count($ingredientCount)->create();

                $ingredients->each(function (Ingredients $ingredient) use ($recipe, $amounts, $units) {
                    $recipe->ingredients()->attach($ingredient->id, [
                        'amount' => fake()->randomElement($amounts),
                        'unit' => fake()->randomElement($units),
                    ]);
                });
            }

            if ($recipe->steps()->count() === 0) {
                // Create some random steps and attach them to the recipe
                $stepCount = fake()->numberBetween(2, 4);
                Step::factory()->for($recipe)->count($stepCount)->create();
            }
        });
    }

    /**
     * Indicate that the recipe should have a specific name.
     */
    public function withName(string $name): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => $name,
        ]);
    }

    /**
     * Indicate that the recipe should have specific steps.
     */
    public function withSteps(array $steps): static
    {
        return $this->state(fn (array $attributes) => [
            'steps' => $steps,
        ]);
    }
}
