<?php

namespace Database\Factories;

use App\Models\Ingredients;
use App\Models\Recipe;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Recipe>
 */
class RecipeFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->words(2, true) . ' Recipe',
            'description' => fake()->paragraph(),
            'author_email' => fake()->safeEmail(),
            'slug' => null, // Will be auto-generated by the model's boot method
            'steps' => [
                fake()->sentence(),
                fake()->sentence(),
                fake()->sentence(),
                fake()->sentence(),
            ],
        ];
    }

    /**
     * Configure the model factory.
     */
    public function configure(): static
    {
        return $this->afterCreating(function (Recipe $recipe) {
            // Only attach default ingredients if none are already attached
            if ($recipe->ingredients()->count() === 0) {
                // Create 3-6 random ingredients and attach them to the recipe
                $ingredientCount = fake()->numberBetween(2, 4);
                $ingredients = Ingredients::factory()->count($ingredientCount)->create();
                $recipe->ingredients()->attach($ingredients->pluck('id'));
            }
        });
    }

    /**
     * Indicate that the recipe should have a specific name.
     */
    public function withName(string $name): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => $name,
        ]);
    }

    /**
     * Indicate that the recipe should have specific steps.
     */
    public function withSteps(array $steps): static
    {
        return $this->state(fn (array $attributes) => [
            'steps' => $steps,
        ]);
    }
}

